name: melody_match
description: A desktop app that recommends music based on uploaded images.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/music/
